@startuml
'https://plantuml.com/activity-diagram-beta

|Người dùng|
start
:Nhấn nút "Xóa chat";

|Hệ thống|
:Hiển thị hộp thoại xác nhận xóa chat;

|Người dùng|
:Chọn "Thực hiện" để xác nhận xóa;

|Hệ thống|
:Gửi yêu cầu xóa chat với người dùng;
:Gửi sự kiện thông báo xóa thành công;

stop
@enduml
