@startuml
'https://plantuml.com/activity-diagram-beta

|Người dùng|
start
:Nhấn nút "Xóa";

|Hệ thống|
:Hiển thị hộp thoại xác nhận xóa;

|Người dùng|
:Chọn "Thực hiện" để xác nhận xóa;

|Hệ thống|
:Gửi sự kiện thông báo xóa thành công;

stop
@enduml
